'use strict';const assert=require('assert/strict'),fs=require('fs');require('../src/core.js');require('../src/world.js');require('../src/product-data.js');const D=global.TF.productData,schema=JSON.parse(fs.readFileSync('agents/v1/pack.schema.json','utf8'));
let activeSchema=schema;
// Dependency-free structural checker for the published schema's JSON Schema keywords.
function validate(s,v,path='$',errors=[]){if(s.$ref){const target=s.$ref.slice(2).split('/').reduce((r,k)=>r[k],activeSchema);validate(target,v,path,errors);}if(s.allOf)s.allOf.forEach(a=>validate(a,v,path,errors));if(s.anyOf&&!s.anyOf.some(a=>validate(a,v,path,[]).length===0))errors.push(path+':anyOf');if(s.if){const applies=validate(s.if,v,path,[]).length===0;if(applies&&s.then)validate(s.then,v,path,errors);else if(!applies&&s.else)validate(s.else,v,path,errors);}if(s.const!==undefined&&v!==s.const)errors.push(path+':const');if(s.enum&&!s.enum.includes(v))errors.push(path+':enum');if(s.type){const types=Array.isArray(s.type)?s.type:[s.type],actual=v===null?'null':Array.isArray(v)?'array':typeof v,ok=types.includes(actual)||types.includes('integer')&&typeof v==='number'&&Number.isInteger(v);if(!ok){errors.push(path+':type');return errors;}}if(typeof v==='string'){if(s.minLength!==undefined&&v.length<s.minLength||s.maxLength!==undefined&&v.length>s.maxLength||s.pattern&&!new RegExp(s.pattern).test(v))errors.push(path+':text');}if(typeof v==='number'){if(!Number.isFinite(v)||s.minimum!==undefined&&v<s.minimum||s.maximum!==undefined&&v>s.maximum||s.exclusiveMinimum!==undefined&&v<=s.exclusiveMinimum)errors.push(path+':number');}if(Array.isArray(v)){if(s.minItems!==undefined&&v.length<s.minItems||s.maxItems!==undefined&&v.length>s.maxItems||s.uniqueItems&&new Set(v.map(JSON.stringify)).size!==v.length)errors.push(path+':array');if(s.items)v.forEach((item,i)=>validate(s.items,item,path+'['+i+']',errors));}else if(v&&typeof v==='object'){for(const k of s.required||[])if(v[k]===undefined)errors.push(path+'.'+k+':required');for(const k of Object.keys(v)){if(s.properties&&s.properties[k])validate(s.properties[k],v[k],path+'.'+k,errors);else if(s.additionalProperties===false)errors.push(path+'.'+k+':unknown');}}return errors;}
for(const name of ['minimal-fictional-pack','two-team-pack']){const pack=JSON.parse(fs.readFileSync('agents/v1/examples/'+name+'.json','utf8'));assert.deepEqual(validate(schema,pack),[]);assert.equal(D.validatePack(pack).ok,true);}
for(const mutate of [p=>p.teams[0].players=null,p=>p.teams[0].lineup=null,p=>p.teams[0].kits.home=null,p=>p.author=null,p=>p.teams[0].players[0].attributes=[],p=>p.teams[0].players[0].attributes.reflexes=101,p=>p.teams[0].players[0].attributes.magic=50]){const pack=D.starterPack();mutate(pack);assert.ok(validate(schema,pack).length);assert.equal(D.validatePack(pack).ok,false);}
const upper=D.starterPack();upper.teams[0].crest='assets/crests/CLUB.PNG';assert.deepEqual(validate(schema,upper),[]);assert.equal(D.validatePack(upper).ok,true);
const cupSchema=JSON.parse(fs.readFileSync('agents/v1/cup-job.schema.json')),job=JSON.parse(fs.readFileSync('agents/v1/examples/cup-job.json'));activeSchema=cupSchema;assert.deepEqual(validate(cupSchema,job),[]);for(const n of [5,6,9])assert.ok(validate(cupSchema,{...job,entrants:Array.from({length:n},(_,i)=>'team-'+i)}).length);const resultSchema=JSON.parse(fs.readFileSync('agents/v1/result.schema.json')),example=JSON.parse(fs.readFileSync('agents/v1/examples/match-result.json'));activeSchema=resultSchema;assert.deepEqual(validate(resultSchema,example),[]);assert.ok(validate(resultSchema,{...example,complete:false}).length);assert.ok(validate(resultSchema,{...example,score:{home:-1,away:0}}).length);
console.log('Published pack schema/examples and shared semantic structural constraints agree for valid examples and malformed shapes.');
