'use strict';const assert=require('assert/strict');for(const f of ['core','analysis','world','tactics','intelligence','physics','rules','telemetry','product-data','engine-facade','product-reports'])require('../src/'+f+'.js');const TF=global.TF,R=TF.productReports,D=TF.productData,teams=D.compilePack(D.starterPack()).teams,h=TF.engine.createMatch({matchId:'report-fixture',seed:1,home:teams[0],away:teams[1],halfSeconds:2700}),p=h.match.players.find(p=>p.teamId===h.match.teams[0].id&&p.positionFamily!=='GK'),tid=p.teamId;const events=[{sequence:1,type:'card',playerId:p.id,teamId:tid,card:'yellow',yellowCount:1,redCount:0,time:600},{sequence:2,type:'card',playerId:p.id,teamId:tid,card:'red',yellowCount:2,redCount:1,time:1200}];const old=TF.engine.readEvents;TF.engine.readEvents=()=>({events});h.match.clock.elapsedSeconds=5400;const reduced=R.reduce(h),row=reduced.players.find(x=>x.id===p.id);TF.engine.readEvents=old;assert.equal(row.stats.yellowCards,2);assert.equal(row.stats.redCards,1);assert.equal(row.minutes,20);const base={minutes:90,stats:{goals:0,assists:0,progressivePasses:10,tackles:10,saves:0,yellowCards:0,redCards:0,miscontrols:0}},def=R.rating({...base,positionFamily:'DEF'}),mid=R.rating({...base,positionFamily:'MID'});assert.equal(def.roleContext,'DEF');assert.notDeepEqual(def.ledger,mid.ledger);for(const bad of [null,{format:'tacticmesh-result',formatVersion:'1.0.0',kind:'match',id:'a',status:'completed',complete:true,score:{home:0,away:0},teams:[null,null],events:[null],players:[null]},{format:'tacticmesh-result',formatVersion:'1.0.0',kind:'cup',id:'a',status:'completed',complete:true,entrants:[null,null,null,null],fixtures:[null,null,null],champion:{}}])assert.equal(R.validateResult(bad).ok,false);const genuine=JSON.parse(require('fs').readFileSync('agents/v1/examples/match-result.json'));assert.equal(R.validateResult(genuine).ok,true);const badRating=D.clone(genuine);badRating.players[0].rating=null;assert.equal(R.validateResult(badRating).ok,false);const badType=D.clone(genuine);badType.events[0].type=22;assert.equal(R.validateResult(badType).ok,false);console.log('Second-yellow cumulative cautions/red/minutes, actual role-context ledger and malformed report guards passed.');
require('./product-keeper-reports.cjs');

(async()=>{
 const identity=require('../tools/engine-version.cjs');TF.ENGINE_BUILD=identity.engineBuild;TF.CORE_BUILD=identity.coreBuild;TF.VERSION=identity.version||'validation-fixture';
 const canonicalPath='.project/reports/documented-match-engine-0d46c50342e4bbc4.json';const canonical=require('fs').existsSync(canonicalPath)?JSON.parse(require('fs').readFileSync(canonicalPath)):genuine;
 assert.equal(R.validateResult(canonical).ok,true,JSON.stringify(R.validateResult(canonical).errors));
 const negatives=[r=>r.teams[0].stats.goals=999,r=>r.regulationScore.home=999,r=>r.winnerId='nonentrant',r=>r.teamSnapshots=[],r=>delete r.engineBuild,r=>r.players[0].teamId='nonentrant',r=>r.teamSnapshots[0].players[0].attributes.reflexes=1,r=>r.ratingModelVersion='unknown',r=>r.formatVersion='2.0.0',r=>r.decisionMethod='extra-time'];
 if(canonical.events.some(e=>e.type==='goal'))negatives.push(r=>r.events.find(e=>e.type==='goal').scorerId=r.players.find(p=>p.teamId===r.teams[1].id).id);if(canonical.ratingModelVersion===R.ratingModelVersion)negatives.push(r=>delete r.keeperMetricsModelVersion);
 for(const mutate of negatives){const bad=D.clone(canonical);mutate(bad);assert.equal(R.validateResult(bad).ok,false,'contradictory canonical clone must reject');}
 assert.equal(R.validateResult(genuine).ok,true,'published original rating/contact model stays readable');
 const ordinary=TF.engine.createMatch({matchId:'current-ordinary-validation',seed:47,home:teams[0],away:teams[1],halfSeconds:.05});await TF.engine.finishSimulation(ordinary);const ordinaryReport=R.fromMatch(ordinary);assert.equal(R.validateResult(ordinaryReport).ok,true,JSON.stringify(R.validateResult(ordinaryReport).errors));
 const tie=TF.engine.createMatch({matchId:'current-physical-tie-validation',seed:71,home:teams[0],away:teams[1],halfSeconds:.05,knockout:true});await TF.engine.finishSimulation(tie);const tieReport=R.fromMatch(tie);assert.equal(tieReport.decisionMethod,'penalties');assert.ok(tieReport.events.some(e=>e.type==='extra-time-period'));assert.ok(tieReport.events.some(e=>e.type==='penalty-goal'));assert.equal(R.validateResult(tieReport).ok,true,JSON.stringify({errors:R.validateResult(tieReport).errors,events:[tieReport.events[30],tieReport.events[76]]}));const wrongPen=D.clone(tieReport);wrongPen.penaltyScore.home++;assert.equal(R.validateResult(wrongPen).ok,false);
 console.log('Current/legacy canonical ordinary and genuine ET/shootout report controls plus score/scorer/winner/snapshot/version contradictions passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
