'use strict';const assert=require('assert/strict'),fs=require('fs'),{Worker:NodeWorker}=require('worker_threads');const identity=require('../tools/engine-version.cjs');for(const f of ['core','analysis','world','tactics','intelligence','physics','rules','telemetry','product-data'])require('../src/'+f+'.js');global.TF.ENGINE_BUILD=identity.engineBuild;global.TF.VERSION='worker-contract-fixture';require('../src/engine-facade.js');require('../src/product-runner.js');require('../src/product-import.js');
class BrowserWorker{constructor(url){this.pending=[];this.closed=false;fetch(url).then(r=>r.text()).then(source=>{if(this.closed)return;this.worker=new NodeWorker('const {parentPort}=require("worker_threads");global.postMessage=x=>parentPort.postMessage(x);parentPort.on("message",data=>global.onmessage({data}));'+source,{eval:true});this.worker.on('message',data=>this.onmessage&&this.onmessage({data}));this.worker.on('error',e=>this.onerror&&this.onerror(e));this.pending.forEach(x=>this.worker.postMessage(x));this.pending=[];}).catch(e=>this.onerror&&this.onerror(e));}postMessage(x){if(this.worker)this.worker.postMessage(x);else this.pending.push(x);}terminate(){this.closed=true;if(this.worker)this.worker.terminate();}}
const TF=global.TF;global.Worker=BrowserWorker;const names=['core','analysis','world','tactics','intelligence','physics','rules','telemetry','product-data','engine-facade'];TF.ENGINE_WORKER_SOURCE='globalThis.TF={ENGINE_BUILD:'+JSON.stringify(identity.engineBuild)+',VERSION:"worker-contract-fixture"};\n'+names.map(f=>fs.readFileSync('src/'+f+'.js','utf8')).join('\n');
(async()=>{assert.equal(typeof TF.engine.restoreCheckpointInto,'function');global.document={};const zip=TF.productImport.zip({'pack.json':JSON.stringify(TF.productData.starterPack()),'LICENSES.txt':'Original fixture'});const importResult=await TF.productImport.stage(zip);assert.equal(importResult.ok,true,JSON.stringify(importResult.errors));delete global.document;const teams=TF.productData.compilePack(TF.productData.starterPack()).teams,config={matchId:'worker-parity',seed:47,home:teams[0],away:teams[1],halfSeconds:.2,knockout:false},main=TF.engine.createMatch(config),worker=TF.engine.createMatch(config),sameMatch=worker.match;let loops=0;while(!main.match.state.finished){const r=TF.engine.stepMatch(main,120);if(r.status==='half-time')TF.engine.continueAfterHalfTime(main);assert.ok(++loops<100);}worker.core.pause();worker.match.clock.running=false;const r=await TF.productRunner.run(worker);assert.equal(r.status,'completed');assert.equal(worker.match,sameMatch);assert.deepEqual(worker.match.score,main.match.score);assert.equal(worker.match.tick,main.match.tick);assert.deepEqual(TF.engine.readEvents(worker,0),TF.engine.readEvents(main,0));const cancel=TF.engine.createMatch(Object.assign({},config,{matchId:'cancel-worker',halfSeconds:2700})),controller=new AbortController();setTimeout(()=>controller.abort(),50);const stopped=await TF.productRunner.run(cancel,{signal:controller.signal});assert.equal(stopped.status,'cancelled');assert.equal(TF.engine.getResult(cancel).complete,false);assert.ok(stopped.checkpoint);const pre=TF.engine.createMatch({...config,matchId:'pre-cancel',halfSeconds:2700}),preAbort=new AbortController();preAbort.abort();const preResult=await TF.productRunner.run(pre,{signal:preAbort.signal});assert.equal(preResult.status,'cancelled');assert.equal(TF.engine.getResult(pre).status,'cancelled');assert.equal(pre.match.tick,0);
// Real serialized worker checkpoints wait for the prior durable-write acknowledgement.
const periodic=TF.engine.createMatch({...config,matchId:'periodic-worker',halfSeconds:.5}),savedCheckpoints=[];let pendingWrites=0,maxPendingWrites=0;
const periodicResult=await TF.productRunner.run(periodic,{chunkTicks:6,checkpointIntervalMs:1,onCheckpoint:async(cp,reason)=>{pendingWrites++;maxPendingWrites=Math.max(maxPendingWrites,pendingWrites);const immutable=structuredClone(cp);await new Promise(resolve=>setTimeout(resolve,4));assert.deepEqual(cp,immutable);savedCheckpoints.push({checkpoint:immutable,reason});pendingWrites--;}});
assert.equal(periodicResult.status,'completed');assert.equal(maxPendingWrites,1);assert.equal(savedCheckpoints[0].reason,'initial');assert.ok(savedCheckpoints.some(c=>c.reason==='half-time'));assert.ok(savedCheckpoints.some(c=>c.reason==='periodic'));const midCheckpoint=savedCheckpoints.find(c=>c.checkpoint.core.tick>0).checkpoint,resumed=TF.engine.restoreCheckpoint(midCheckpoint);await TF.engine.finishSimulation(resumed,{chunkTicks:6});assert.equal(resumed.match.tick,periodic.match.tick);assert.deepEqual(TF.engine.readEvents(resumed,0),TF.engine.readEvents(periodic,0));assert.deepEqual(resumed.match.score,periodic.match.score);
// A dead worker's cancel watchdog restores the latest verified checkpoint, not kickoff.
const NormalWorker=global.Worker;class SilentCancelledWorker extends NormalWorker{postMessage(message){if(message.type==='cancel'){this.terminate();return;}super.postMessage(message);}}
global.Worker=SilentCancelledWorker;const watchdog=TF.engine.createMatch({...config,matchId:'checkpoint-watchdog',halfSeconds:2700}),watchdogAbort=new AbortController();let latestVerified=null;const recovered=await TF.productRunner.run(watchdog,{chunkTicks:6,checkpointIntervalMs:1,signal:watchdogAbort.signal,onCheckpoint:async(cp)=>{latestVerified=structuredClone(cp);if(cp.core.tick>0)watchdogAbort.abort();}});assert.equal(recovered.status,'cancelled');assert.equal(recovered.recoveredFromLatestCheckpoint,true);assert.ok(latestVerified.core.tick>0);assert.equal(watchdog.match.tick,latestVerified.core.tick);global.Worker=NormalWorker;
for(const name of ['product-storage','product-reports','product-cup','product'])require('../src/'+name+'.js');const P=TF.product;await P.ready;
// A failed checkpoint transaction must leave its preceding real checkpoint intact.
const failHandle=P.startMatch({seed:47,matchId:'failed-worker-write',halfSeconds:.5}),commit=P.store.commit;let writeCount=0;P.store.commit=async function(ops,...rest){if(ops.some(op=>op.store==='checkpoints'&&!op.remove)&&++writeCount===2){const error=new Error('quota fixture: older data preserved');error.code='STORAGE_WRITE_FAILED';throw error;}return commit.call(this,ops,...rest);};await assert.rejects(P.finishMatch(failHandle,{chunkTicks:6,checkpointIntervalMs:1}),e=>e.code==='STORAGE_WRITE_FAILED'&&e.checkpointPersistenceFailed);P.store.commit=commit;assert.equal(P.store.get('checkpoints',failHandle.match.id).checkpoint.core.tick,0);assert.equal(failHandle.match.tick,0);assert.equal(TF.engine.getResult(failHandle).complete,false);assert.match(P.storageStatus().status,/failed/);
// Chunked fallback persists equivalent causal checkpoints without queued writes.
const fallback=P.startMatch({seed:47,matchId:'fallback-periodic',halfSeconds:.5}),fallbackRecords=[];pendingWrites=0;maxPendingWrites=0;P.store.commit=async function(ops,...rest){pendingWrites++;maxPendingWrites=Math.max(maxPendingWrites,pendingWrites);await new Promise(resolve=>setTimeout(resolve,2));const result=await commit.call(this,ops,...rest);for(const op of ops)if(op.store==='checkpoints'&&!op.remove)fallbackRecords.push(structuredClone(op.value.checkpoint));pendingWrites--;return result;};const fallbackResult=await P.finishMatch(fallback,{forceMainThread:true,checkpointIntervalMs:1});P.store.commit=commit;assert.equal(fallbackResult.complete,true);assert.equal(maxPendingWrites,1);assert.ok(fallbackRecords.length>=2);assert.ok(fallbackRecords.some(cp=>cp.core.state.halfTime));const fallbackRestore=TF.engine.restoreCheckpoint(fallbackRecords.find(cp=>cp.core.tick>0));await TF.engine.finishSimulation(fallbackRestore);assert.deepEqual(TF.engine.readEvents(fallbackRestore,0),TF.engine.readEvents(fallback,0));
// Synchronous browser security denial is startup failure, with an exact main-thread fallback.
let deniedConstructions=0;class DeniedWorker{constructor(){deniedConstructions++;const error=new Error('Worker constructor denied');error.name='SecurityError';error.code=18;throw error;}}
const denied=P.startMatch({seed:47,matchId:'constructor-denied-fallback',halfSeconds:.5}),deniedInitial=TF.engine.saveCheckpoint(denied),deniedReference=TF.engine.restoreCheckpoint(deniedInitial),deniedProgress=[];
global.Worker=DeniedWorker;
try{
  const rejectedHandle=TF.engine.restoreCheckpoint(deniedInitial),rejectedInitial=TF.captureCheckpoint(rejectedHandle.match);
  await assert.rejects(TF.productRunner.run(rejectedHandle),error=>error.code==='WORKER_START_FAILED'&&error.cause.name==='SecurityError');
  assert.deepEqual(TF.captureCheckpoint(rejectedHandle.match),rejectedInitial,'constructor failure does not advance football or consume its RNG');
  const completedFallback=await P.finishMatch(denied,{checkpointIntervalMs:1,onProgress:s=>deniedProgress.push(s.tick)});
  assert.equal(completedFallback.complete,true);assert.ok(deniedProgress.some(t=>t>0),'fallback still provides real progress');
  await TF.engine.finishSimulation(deniedReference);
  assert.deepEqual(TF.engine.readEvents(denied,0),TF.engine.readEvents(deniedReference,0));
  assert.deepEqual(TF.captureCheckpoint(denied.match),TF.captureCheckpoint(deniedReference.match),'startup fallback follows the exact locked causal suffix');
  const cancelledFallback=P.startMatch({seed:47,matchId:'constructor-denied-cancel',halfSeconds:2700}),abortFallback=new AbortController();
  const cancelledResult=await P.finishMatch(cancelledFallback,{signal:abortFallback.signal,onProgress:()=>abortFallback.abort()});
  assert.equal(cancelledResult.status,'cancelled');assert.equal(cancelledResult.complete,false);assert.ok(cancelledFallback.match.tick>0);
  assert.equal(P.store.get('checkpoints',cancelledFallback.match.id).checkpoint.core.tick,cancelledFallback.match.tick,'fallback cancellation saves actual progress');
}finally{global.Worker=NormalWorker;}
assert.ok(deniedConstructions>=3);
// Engine/job failures remain failures: they cannot become successful fallback reports.
class JobFailedWorker{constructor(){}postMessage(){queueMicrotask(()=>this.onmessage({data:{type:'error',message:'Explicit worker job failure'}}));}terminate(){}}
global.Worker=JobFailedWorker;const jobFailed=P.startMatch({seed:47,matchId:'worker-job-failure-no-fallback',halfSeconds:.5});
try{await assert.rejects(P.finishMatch(jobFailed),e=>e.code==='SIMULATION_ERROR');assert.equal(jobFailed.match.tick,0);assert.equal(P.listResults().some(r=>r.id===jobFailed.match.id),false);}finally{global.Worker=NormalWorker;}
const afterDenied=TF.engine.createMatch({...config,matchId:'worker-after-denial'});assert.equal((await TF.productRunner.run(afterDenied)).status,'completed','failed startup releases busy state for a subsequent real worker');
// An in-flight cup checkpoint is readable from stored state before fixture completion.
const library=P.listTeams(),copies=[await P.duplicateTeam(library[0].libraryId),await P.duplicateTeam(library[1].libraryId)],cup=await P.createCup({name:'Checkpoint reload fixture',entrantIds:[library[0].libraryId,library[1].libraryId,...copies.map(c=>c.team.libraryId)],seed:71,draw:'manual',halfSeconds:1}),cupHandle=await P.nextCupMatch(cup),cupAbort=new AbortController();let checkpointedTick=null;P.store.commit=async function(ops,...rest){const result=await commit.call(this,ops,...rest);for(const op of ops)if(op.store==='checkpoints'&&!op.remove&&op.value.id===cupHandle.match.id&&op.value.checkpoint.core.tick>0){checkpointedTick=op.value.checkpoint.core.tick;cupAbort.abort();}return result;};const cupCancelled=await P.finishMatch(cupHandle,{signal:cupAbort.signal,checkpointIntervalMs:1,chunkTicks:6});P.store.commit=commit;assert.equal(cupCancelled.status,'cancelled');assert.ok(checkpointedTick>0);assert.equal(P.store.get('cups',cup.id).completedFixtures,0);const stored=P.store.get('checkpoints',cupHandle.match.id);assert.equal(stored.cupId,cup.id);assert.equal(stored.fixtureId,cupHandle.fixtureId);assert.ok(stored.checkpoint.core.tick>0);clearInterval(cupHandle._cupLeaseTimer);P.activeMatch=null;const reloadedCup=P.store.get('cups',cup.id),continued=await P.nextCupMatch(reloadedCup);assert.equal(continued.match.tick,stored.checkpoint.core.tick);const parallel=TF.engine.restoreCheckpoint(stored.checkpoint);parallel.status='running';parallel.core.resume();parallel.match.clock.running=true;continued.core.resume();continued.match.clock.running=true;TF.engine.stepMatch(parallel,30);TF.engine.stepMatch(continued,30);assert.deepEqual(TF.captureCheckpoint(continued.match),TF.captureCheckpoint(parallel.match));clearInterval(continued._cupLeaseTimer);await P.releaseCompetition(cup.id);P.activeMatch=null;
console.log('Real worker/fallback periodic checkpoints, serialized writes, quota retention, latest-checkpoint watchdog recovery and cup reload suffix parity passed.');})().catch(e=>{console.error(e);process.exitCode=1;});
