const { spawnSync } = require('node:child_process');
const path = require('node:path');
const tests = [
  'tests/engine-facade.cjs',
  'tests/intelligence-smoke.cjs',
  'tests/stationary-ball-recovery.cjs',
  'tests/shot-keeper-threat.cjs',
  'tests/tactics-smoke.cjs',
  'tests/recovery-target-deep-carrier.cjs',
  'tests/central-cover-reservation.cjs',
  'tests/press-marked-incumbent.cjs',
  'tests/press-reservation-rerank.cjs',
  'tests/ui-production-details.cjs',
  'tests/football-scenarios.cjs',
  'tests/lab-neutral-affiliation.cjs',
  'tests/hidden-team-belief.cjs',
  'tests/physics-rules-smoke.cjs',
  'tests/restart-kick-readiness.cjs',
  'tests/restart-pass-lock-risk.cjs',
  'tests/restart-contact-order.cjs',
  'tests/rules-complete.cjs',
  'tests/goal-kick-opponent-spacing.cjs',
  'tests/goal-attribution-after-contact.cjs',
  'tests/assist-receiver-provenance.cjs',
  'tests/keeper-handling-provenance.cjs',
  'tests/camera-smoke.cjs',
  'tests/renderer-upright.cjs',
  'tests/presentation-smoke.cjs',
  'tests/acceptance.cjs',
  'tests/foundation-contracts.cjs',
  'tests/integration-behavior.cjs',
  'tests/batch-generated-defaults.cjs',
  'tests/physics-execution.cjs',
  'tests/keeper-urgent-belief.cjs',
  'tests/keeper-depth-return.cjs',
  'tests/keeper-controlled-challenge.cjs',
  'tests/keeper-risk-and-one-on-one.cjs',
  'tests/fast-owner-coherence.cjs',
  'tests/challenge-selection-recovery.cjs',
  'tests/press-contact-commitment.cjs',
  'tests/throughball-lead-coherence.cjs',
  'tests/observed-run-pass-sync.cjs',
  'tests/telemetry-pass-lifecycle.cjs',
  'tests/telemetry-shot-xg.cjs',
  'tests/telemetry-event-cursor.cjs',
  'tests/behavior-auditor.cjs',
  'tests/shared-analysis.cjs',
  'tests/labs-boot-smoke.cjs',
  'tests/physics-lab-scenarios.cjs',
  'tests/regressions-batch-cancel.cjs',
  'tests/event-time.cjs',
  'tests/event-feed.cjs',
  'tests/ui-event-feed.cjs',
  'tests/pack-creator-kit.cjs',
  'tests/release-acceptance.cjs'
];
for (const file of tests) {
  const result = spawnSync(process.execPath, [path.resolve(__dirname, '..', file)], { stdio: 'inherit' });
  if (result.status !== 0) process.exit(result.status || 1);
}
process.stdout.write(`all ${tests.length} test programs passed\n`);
