(function(root){'use strict';var TF=root.TF=root.TF||{},D=TF.productData,stores=['teams','assets','matches','cups','checkpoints','meta'];
 function Store(){this.db=null;this.mode='memory';this.status='Ready in memory; export a backup to keep your work.';this.revision=0;this.cache={};stores.forEach(function(s){this.cache[s]=new Map();},this);this.owner='tab-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);this.channel=null;}
 Store.prototype.open=async function(){var self=this;if(!root.indexedDB)return this;try{this.db=await new Promise(function(resolve,reject){var request=indexedDB.open('tacticmesh-local',1);request.onupgradeneeded=function(){stores.forEach(function(s){if(!request.result.objectStoreNames.contains(s))request.result.createObjectStore(s,{keyPath:'id'});});};request.onsuccess=function(){resolve(request.result);};request.onerror=function(){reject(request.error);};request.onblocked=function(){reject(new Error('Close an older TacticMesh tab before opening this library.'));};});this.db.onversionchange=function(){self.db.close();self.db=null;self.status='Storage version changed in another tab. Reload before saving.';};this.mode='indexeddb';await this.reload();this.status='Saved on this device';if(root.BroadcastChannel){this.channel=new BroadcastChannel('tacticmesh-library');this.channel.onmessage=function(e){if(e.data.owner!==self.owner&&e.data.revision>self.revision){self.status='Another tab changed this library. Refresh before saving.';if(self.onchange)self.onchange('conflict');}};}}catch(e){this.db=null;this.mode='memory';this.status='Local storage unavailable. Playing in memory; export a backup to keep your work.';this.error=e.message;}return this;};
 Store.prototype.reload=async function(){var self=this;if(!this.db)return this;var data=await new Promise(function(resolve,reject){var tx=self.db.transaction(stores,'readonly'),all={};stores.forEach(function(s){var req=tx.objectStore(s).getAll();req.onsuccess=function(){all[s]=req.result;};});tx.oncomplete=function(){resolve(all);};tx.onerror=function(){reject(tx.error);};tx.onabort=function(){reject(tx.error);};});stores.forEach(function(s){self.cache[s]=new Map(data[s].map(function(r){return[r.id,r];}));});this.revision=(this.cache.meta.get('revision')||{}).value||0;this.status='Saved on this device';return this;};
 Store.prototype.list=function(store){return Array.from(this.cache[store].values()).map(function(v){return structured(v);});};Store.prototype.get=function(store,id){var v=this.cache[store].get(id);return v?structured(v):null;};
 function structured(v){if(typeof root.structuredClone==='function')return root.structuredClone(v);return JSON.parse(JSON.stringify(v));}
 Store.prototype.commit=async function(operations,expected){var self=this,revision=expected==null?this.revision:expected;if(this.db){await new Promise(function(resolve,reject){var tx=self.db.transaction(stores,'readwrite'),meta=tx.objectStore('meta'),req=meta.get('revision'),conflict=false;req.onsuccess=function(){if(((req.result||{}).value||0)!==revision){conflict=true;tx.abort();return;}operations.forEach(function(op){if(op.remove)tx.objectStore(op.store).delete(op.id);else tx.objectStore(op.store).put(op.value);});meta.put({id:'revision',value:revision+1});};tx.oncomplete=resolve;tx.onabort=function(){var e=new Error(conflict?'Another tab changed this library. Refresh and review before saving.':'Local save failed. Older saved data is preserved; export a backup.');e.code=conflict?'STORAGE_CONFLICT':'STORAGE_WRITE_FAILED';reject(e);};tx.onerror=function(){};});}else if(this.mode!=='memory')throw new Error(this.status);else if(revision!==this.revision){var error=new Error('Local write conflict; refresh and retry.');error.code='STORAGE_CONFLICT';throw error;}operations.forEach(function(op){if(op.remove)self.cache[op.store].delete(op.id);else self.cache[op.store].set(op.value.id,structured(op.value));});this.revision=revision+1;this.cache.meta.set('revision',{id:'revision',value:this.revision});this.status=this.db?'Saved on this device':'Kept in memory; export a backup to save your work.';if(this.channel)this.channel.postMessage({owner:this.owner,revision:this.revision});if(this.onchange)this.onchange('saved');return{ok:true,revision:this.revision,mode:this.mode,status:this.status};};
 Store.prototype.estimate=async function(){if(root.navigator&&navigator.storage&&navigator.storage.estimate)return navigator.storage.estimate();return{usage:null,quota:null};};Store.prototype.requestPersistence=async function(){return !!(root.navigator&&navigator.storage&&navigator.storage.persist&&await navigator.storage.persist());};
 Store.prototype.acquire=async function(id){var key='lock:'+id,now=Date.now(),current=this.get('meta',key);if(current&&current.owner!==this.owner&&current.expires>now){var e=new Error('This competition is running in another tab. Close it or wait for its lease to expire.');e.code='COMPETITION_LOCKED';throw e;}await this.commit([{store:'meta',value:{id:key,owner:this.owner,expires:now+60000}}]);return true;};
 Store.prototype.release=async function(id){var key='lock:'+id,current=this.get('meta',key);if(current&&current.owner===this.owner)await this.commit([{store:'meta',remove:true,id:key}]);};
 TF.productStorage={Store:Store,stores:stores.filter(function(s){return s!=='meta';})};
})(typeof window!=='undefined'?window:globalThis);
